<a href="https://colab.research.google.com/github/Gloou-ui/NM/blob/main/%D0%9B%D0%A0_4_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_17_%D0%9B%D0%B8%D1%82%D0%B2%D0%B8%D0%BD_%D0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутнім на парі

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
matrix = np.random.randint(1,9, size=(3,3))

matrix

array([[7, 7, 1],
       [5, 2, 2],
       [8, 2, 1]])

In [ ]:
bet = np.linalg.det(matrix)
bet

np.float64(57.00000000000001)

In [ ]:
product = np.prod(matrix)
product

np.int64(15680)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(15680)

In [ ]:
sum_1 = np.sum(matrix)

sum_1

np.int64(35)

In [ ]:
np.max(matrix)

np.int64(8)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(3.888888888888889)

In [ ]:
np.sqrt(matrix)

array([[2.64575131, 2.64575131, 1.        ],
       [2.23606798, 1.41421356, 1.41421356],
       [2.82842712, 1.41421356, 1.        ]])

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print(row_sums)

[[15]
 [ 9]
 [11]]


In [ ]:
vector=np.random.randint(1, 10, size=25)
vector

array([5, 6, 7, 9, 7, 6, 8, 8, 3, 5, 4, 8, 4, 9, 4, 3, 9, 8, 5, 6, 6, 9,
       6, 4, 7])

In [ ]:
sorted_vector = np.sort(vector)
sorted_vector

array([3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9,
       9, 9, 9])

In [ ]:
from scipy import stats
mod=stats.mode(vector)
median=np.median(vector)
print(mod)
print(median)

ModeResult(mode=np.int64(6), count=np.int64(5))
6.0


In [ ]:
a = np.array([[1, 2, -1], [3, 4, 1], [5, 1, -3]])
b = np.array([-3, 1, -2])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [ 1. -1.  2.]
Матричний метод [ 1. -1.  2.]


In [ ]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
           modified_a = np.copy(a)
           modified_a[:, i] = b
           solutions.append(round(np.linalg.det(modified_a) / det_a, 1))
        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else: print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(1.0), np.float64(-1.0), np.float64(2.0)]
